# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.


name: Generate changelog
run-name: Generate changelog

on:
  workflow_call:

jobs:
  compose_changelog:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          configuration: '.github/.changelog-config.json'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update changelog in release
        id: update_release1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
        run: |

          # Extract repository owner and name.
          REPO_OWNER=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f1)
          REPO_NAME=$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2)

          # Create a JSON payload with the new release body content
          PAYLOAD=$(jq -n --arg body "${{ steps.build_changelog.outputs.changelog }}" '{body: $body}')

          # Update the release
          UPDATE_RESPONSE=$(curl -s -X PATCH -H "Authorization: token ${GITHUB_TOKEN}" \
            -H "Content-Type: application/json" \
            -d "$PAYLOAD" \
            "https://api.github.com/repos/${REPO_OWNER}/${REPO_NAME}/releases/${RELEASE_ID}")
